"""sessions table

Retrofitted migration: the `sessions` table (app/storage/models.py's
SessionRow) has existed since M1 but was never migration-tracked -- it was
created solely by app/main.py's lifespan calling `Base.metadata.create_all()`
on startup, unlike `officers`/`officer_sessions` (a1b2c3d4e5f6), which got a
real migration the same day. That gap is what this migration closes: a
clean checkout, CI, or a from-scratch DB rebuild had no way to get this
table (or its indexes, including `ix_sessions_started_at`, added for
app/storage/dashboard_repository.py's date-range queries) via
`alembic upgrade head` alone.

Autogenerated against a genuinely fresh database (no `sessions` table) so
the diff is the real one, not hand-transcribed from the model -- see the
session's own verification notes for the fresh-DB upgrade/downgrade run.

The already-running dev DB, which already had this table and index (the
table from create_all(), the index from a manual `CREATE INDEX` applied
directly -- exactly the gap being closed here) was `alembic stamp`ped to
this revision rather than re-run: the DDL below is for every OTHER
environment from this point forward.

Revision ID: 9d17cd0a007b
Revises: a1b2c3d4e5f6
Create Date: 2026-09-01 21:17:36.851985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d17cd0a007b'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'sessions',
        sa.Column('session_id', sa.String(), primary_key=True),
        sa.Column('lane_id', sa.String(), nullable=False),
        sa.Column('officer_id', sa.String(), nullable=False),
        sa.Column('started_at', sa.String(), nullable=False),
        sa.Column('band', sa.String(), nullable=True),
        sa.Column('sealed', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
    )
    op.create_index('ix_sessions_lane_id', 'sessions', ['lane_id'])
    op.create_index('ix_sessions_officer_id', 'sessions', ['officer_id'])
    op.create_index('ix_sessions_sealed', 'sessions', ['sealed'])
    # app/storage/dashboard_repository.py range-filters every dashboard
    # query on this column -- the one index this table was actually
    # missing on the live dev DB before this migration existed.
    op.create_index('ix_sessions_started_at', 'sessions', ['started_at'])


def downgrade() -> None:
    op.drop_index('ix_sessions_started_at', table_name='sessions')
    op.drop_index('ix_sessions_sealed', table_name='sessions')
    op.drop_index('ix_sessions_officer_id', table_name='sessions')
    op.drop_index('ix_sessions_lane_id', table_name='sessions')
    op.drop_table('sessions')
